codecov:
  require_ci_to_pass: yes

github_checks:
  annotations: true

coverage:
  precision: 2
  round: down
  range: "50...90"
  status:
    patch: true
    project:
      # Flags should match those passed to codecov/codecov-action in CI
      backend:
        flags:
          - unittests

flags:
  unittests:
    paths:
      # Accepts only glob patterns, not regex
      - "internal/**"
      - "cmd/**"
    carryforward: true
