name: Golang Unit and Integration Tests
on:
  push:
    branches:
      - "master"
    paths:
      - "**.go"
      - "**.golden"
  pull_request:
    branches:
      - "master"
    paths:
      - "**.go"
      - "**.golden"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  golangci:
    strategy:
      matrix:
        go: [1.23]
        os: [ubuntu-24.04]
    name: golangci-lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63
          args: --config=.golangci.yml --timeout=10m
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-24.04
    needs: golangci
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install lynx for xdg-open support
        run: sudo apt-get install lynx
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - name: Run coverage
        run: go test --short ./... -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.3.0
        with:
          files: ./coverage.txt
          flags: unittests


