name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    if: github.repository == 'meshery-extensions/meshery-mcp-server' && github.event_name != 'pull_request_target'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Drafting release
        uses: release-drafter/release-drafter@v7
        with:
          config-name: release-drafter.yml

  autolabel:
    if: github.repository == 'meshery-extensions/meshery-mcp-server' && github.event_name == 'pull_request_target'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Autolabel pull request
        uses: release-drafter/release-drafter/autolabeler@v7
        with:
          config-name: release-drafter.yml
